const faqs = [
    {
      id: 1,
      question: "How does the Revenue Share work?",
      answer:
        "If you choose to integrate the individual plan, you as the server owner will receive 25% of the revenue generated by your server. This is a great way to add a new revenue stream to your server.",
    },
    {
        id: 2,
        question: "How can I set limits on usage?",
        answer:
          "If you choose to integrate the Enterprise plan, you as the server owner will be able to set limits on calls per user per month on the Server Owner Dashboard.",
      },

      {
        id: 3,
        question: "Can I cancel the individual plan at any time?",
        answer:
            "Yes, you can cancel the individual plan at any time. If you cancel the plan, you will no longer receive revenue from your server.",
      },
      {
        id: 4,
        question: "What happens if I exceed the call limit?",
        answer:
          "You will be billed for another $2.89 per 60 calls.",
      },
  ]
  
  export default function FAQ() {
    return (
      <div className="bg-white">
        <div className="mx-auto max-w-6xl py-12 px-4 sm:py-20 sm:px-6 lg:px-8" data-aos='zoom-y-out' data-aos-delay='150'>
          <div className="max-w-2xl lg:mx-auto lg:text-center">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Frequently asked questions</h2>
          </div>
          <div className="md:mt-20 sm:mt-16 mt-10">
            <dl className="space-y-10 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:gap-y-10 lg:space-y-0">
              {faqs.map((faq) => (
                <div key={faq.id}>
                  <dt className="font-semibold text-gray-900">{faq.question}</dt>
                  <dd className="mt-3 text-gray-600">{faq.answer}</dd>
                </div>
              ))}
            </dl>
          </div>
        </div>
      </div>
    )
  }
  